- hosts: web
  remote_user: vivil
  become: yes
  tasks:
      - name: change hostname
        hostname: name={{web_domain}}
      - name: install nginx
        apt: name=nginx state=latest
        notify: restart nginx
      - name: install ufw
        apt: name=ufw state=latest
      - name: Configure ufw defaults
        ufw: direction={{ item.direction }} policy={{ item.policy }}
        with_items:
            - { direction: 'incoming', policy: 'deny' }
            - { direction: 'outgoing', policy: 'allow' }
      - name: Configure ufw rules
        ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }} state=enabled
        with_items:
            - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
            - { rule: 'allow', port: '80', proto: 'tcp' }
        notify:
            - restart ufw
  handlers:
      - name: restart nginx
        service: name=nginx state=restarted
      - name: enable ufw
        service: name=ufw state=restarted
